# Autogenerated from the following stub : git/ql_rest/gensrc/stubs/stub.qlrest.python_module

# ohutils_py
# ohutils_py


import json
from json import JSONEncoder

class ohVersion(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.Trigger = False;

    def default(self, o):
        return o.__dict__
