# Autogenerated from the following stub : gensrc/stubs/stub.qlrest.python_module

# piecewiseyieldcurve_py
# piecewiseyieldcurve_py


import json
from json import JSONEncoder

class qlPiecewiseYieldCurve(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.NDays = 0;
        self.Calendar = "";
        self.RateHelpers = [];
        self.DayCounter = "";
        self.Jumps = [];
        self.JumpDates = [];
        self.Accuracy = 0.0;
        self.TraitsID = "";
        self.InterpolatorID = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlPiecewiseYieldCurveMixedInterpolation(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.NDays = 0;
        self.Calendar = "";
        self.RateHelpers = [];
        self.DayCounter = "";
        self.Jumps = [];
        self.JumpDates = [];
        self.Accuracy = 0.0;
        self.TraitsID = "";
        self.InterpolatorID = "";
        self.MixedInterpolationBehavior = "";
        self.PillarsBeforeChange = 0;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__
