# Autogenerated from the following stub : gensrc/stubs/stub.qlrest.python_module

# processes_py
# processes_py


import json
from json import JSONEncoder

class qlGeneralizedBlackScholesProcess(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.BlackVolID = "";
        self.Underlying = 0.0;
        self.DayCounter = "";
        self.SettlementDate = "";
        self.RiskFreeRate = 0.0;
        self.DividendYield = 0.0;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__
