# Autogenerated from the following stub : gensrc/stubs/stub.qlrest.python_module

# ratehelpers_py
# ratehelpers_py


import json
from json import JSONEncoder

class qlBondHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Price = 0.0;
        self.Bond = "";
        self.UseCleanPrice = False;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlDatedOISRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.StartDate = "";
        self.EndDate = "";
        self.FixedRate = 0.0;
        self.ONIndex = "";
        self.DiscountingCurve = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlDepositRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Rate = 0.0;
        self.IborIndex = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlDepositRateHelper2(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Rate = 0.0;
        self.Tenor = "";
        self.FixingDays = 0;
        self.Calendar = "";
        self.Convention = "";
        self.EndOfMonth = False;
        self.DayCounter = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFixedRateBondHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Price = 0.0;
        self.SettlementDays = 0;
        self.FaceAmount = 0.0;
        self.ScheduleID = "";
        self.Coupons = [];
        self.DayCounter = "";
        self.PaymentBDC = "";
        self.Redemption = 0.0;
        self.IssueDate = "";
        self.PaymentCalendar = "";
        self.ExCouponPeriod = "";
        self.ExCouponCalendar = "";
        self.ExCouponBDC = "";
        self.ExCouponEndOfMonth = False;
        self.UseCleanPrice = False;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFraRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Rate = 0.0;
        self.PeriodToStart = "";
        self.IborIndex = "";
        self.PillarDate = "";
        self.CustomPillarDate = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFraRateHelper2(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Rate = 0.0;
        self.PeriodToStart = "";
        self.LengthInMonths = 0;
        self.FixingDays = 0;
        self.Calendar = "";
        self.Convention = "";
        self.EndOfMonth = False;
        self.DayCounter = "";
        self.PillarDate = "";
        self.CustomPillarDate = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFuturesRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Price = 0.0;
        self.FuturesType = "";
        self.FuturesDate = "";
        self.IborIndex = "";
        self.ConvexityAdjQuote = 0.0;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFuturesRateHelper2(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Price = 0.0;
        self.FuturesType = "";
        self.FuturesDate = "";
        self.LengthInMonths = 0;
        self.Calendar = "";
        self.Convention = "";
        self.EndOfMonth = False;
        self.DayCounter = "";
        self.ConvexityAdjQuote = 0.0;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFuturesRateHelper3(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Price = 0.0;
        self.FuturesType = "";
        self.FuturesDate = "";
        self.EndDate = "";
        self.DayCounter = "";
        self.ConvexityAdjQuote = 0.0;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlFxSwapRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.FwdPoint = 0.0;
        self.SpotFx = 0.0;
        self.Tenor = "";
        self.FixingDays = 0;
        self.Calendar = "";
        self.Convention = "";
        self.EndOfMonth = False;
        self.IsFxBaseCurrencyCollateralCurrency = False;
        self.CollateralCurve = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlOISRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.SettlDays = 0;
        self.Tenor = "";
        self.FixedRate = 0.0;
        self.ONIndex = "";
        self.DiscountingCurve = "";
        self.TelescopicValueDates = False;
        self.PaymentLag = 0;
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlRateHelperImpliedQuote(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Trigger = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlRateHelperQuoteError(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Trigger = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlRateHelperQuoteIsValid(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Trigger = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlRateHelperQuoteName(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Trigger = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlRateHelperQuoteValue(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Trigger = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlSwapRateHelper(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Rate = 0.0;
        self.SwapIndex = "";
        self.Spread = 0.0;
        self.ForwardStart = "";
        self.DiscountingCurve = "";
        self.PillarDate = "";
        self.CustomPillarDate = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlSwapRateHelper2(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.Rate = 0.0;
        self.SettlDays = 0;
        self.Tenor = "";
        self.Calendar = "";
        self.FixedLegFrequency = "";
        self.FixedLegConvention = "";
        self.FixedLegDayCounter = "";
        self.IborIndex = "";
        self.Spread = 0.0;
        self.ForwardStart = "";
        self.DiscountingCurve = "";
        self.PillarDate = "";
        self.CustomPillarDate = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__
