# Autogenerated from the following stub : ql_rest/gensrc/stubs/stub.qlrest.python_module

# schedule_py
# schedule_py


import json
from json import JSONEncoder

class qlSchedule(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.EffectiveDate = "";
        self.TerminationDate = "";
        self.Tenor = "";
        self.Calendar = "";
        self.Convention = "";
        self.TermDateConv = "";
        self.GenRule = "";
        self.EndOfMonth = False;
        self.FirstDate = "";
        self.NextToLastDate = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlScheduleFromDateVector(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.EffectiveDate = [];
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__

import json
from json import JSONEncoder

class qlScheduleTruncated(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.OriginalSchedule = "";
        self.TruncationDate = "";
        self.Permanent = False;
        self.Trigger = False;
        self.Overwrite = False;

    def default(self, o):
        return o.__dict__
