# Autogenerated from the following stub : gensrc/stubs/stub.qlrest.python_module

# valueobjects_py
# valueobjects_py


import json
from json import JSONEncoder

class ohObjectPropertyValues2(JSONEncoder):

    def __init__(self):
        self.instanceID = ""
        
        self.ObjectId = "";
        self.PropertyName = "";
        self.Trigger = False;

    def default(self, o):
        return o.__dict__
