version: '2'
services:
  options_monitor:
    image: ghcr.io/mkipnis/ql_rest:latest
    #image: ql_rest
    command: ["bash", "-c", "cd /ql_rest/Examples/options_monitor/options_pricer_proxy/scripts; ./update_yfinance_and_save_demo_data.sh; cd /ql_rest/Examples/options_monitor/; LD_LIBRARY_PATH=/usr/local/lib ./start_options_monitor.sh"]
    ports:
      - 8000:8000
