version: '2'
services:
  options_monitor:
    image: ghcr.io/mkipnis/ql_rest:latest
    #image: ql_rest
    command: ["bash", "-c", "cd /ql_rest/Examples/options_monitor/options_pricer_proxy/scripts; python3 save_demo_data.py; cd /ql_rest/Examples/options_monitor/; ./start_options_monitor.sh"]
    ports:
      - 8000:8000

  swap_designer:
    image: ghcr.io/mkipnis/ql_rest:latest
    command: ["bash", "-c", "cd /ql_rest/Examples/swap_designer/; ./run_designer.sh"]
    ports:
      - 3000:3000
      - 7922:7922
