version: '2'
services:
  options_monitor:
    image: ql_rest
    command: ["bash", "-c", "cd /ql_rest/Examples/options_monitor/; ./start_options_monitor.sh"]
    volumes:
      - $PWD:/opt/workspace
    ports:
      - 8000:8000

  swap_designer:
    image: ql_rest
    command: ["bash", "-c", "cd /ql_rest/Examples/swap_designer/; ./run_designer.sh"]
    volumes:
      - $PWD:/opt/workspace
    ports:
      - 3000:3000
      - 7922:7922
