version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - pricing_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  options_pricer_py:
    image: ghcr.io/mkipnis/ql_rest_opt_pricer_py:latest
    networks:
      - pricing_net
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
      restart_policy:
        condition: any
    ports:
      - target: 8000
        published: 18000
        protocol: tcp
        mode: ingress

  options_pricer_cpp:
    image: ghcr.io/mkipnis/ql_rest_opt_pricer_cpp:latest
    networks:
      - pricing_net
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
      restart_policy:
        condition: any
    ports:
      - target: 8000
        published: 28000
        protocol: tcp
        mode: ingress

networks:
  pricing_net:
    driver: overlay
    attachable: true

volumes:
  redis_data:
